/**
 * Deterministic assembler for the Aemeath skin bundle.
 *
 * No external toolchain: the client bundle is emitted in the exact
 * __ModuleLoader__ factory format the dsh web shell consumes (same contract
 * as the tsdown pipeline of the upstream skins), and the stylesheet is
 * inlined with the loader-owned <style data-plugin> convention so the HMR
 * driver removes it on unload.
 *
 * Inputs  : assets/*.webp, src/client/{art.js,index.js}, src/client/aemeath.css
 * Outputs : src/client/background-art.generated.js (source-parity record),
 *           lib/client.js, lib/index.js
 */
import { readFile, writeFile, mkdir, stat } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const PACKAGE_NAME = '@dsh-external/dsh-client-ui-skin-aemeath'
const CSS_TAG_ID = `${PACKAGE_NAME}/src/client/aemeath.css`

const region = (name, body) => `\t\t//#region ${name}\n${body}\n\t\t//#endregion`

const read = async (p) => readFile(join(ROOT, p), 'utf8')
const write = async (p, body) => {
  await mkdir(dirname(join(ROOT, p)), { recursive: true })
  await writeFile(join(ROOT, p), body)
}

function indentBlock(source, prefix = '\t\t') {
  return source.replace(/^(?!\s*$)/gm, prefix)
}

/* 1. Raster wallpapers & marks → data URIs + generated source module. */
const chat = await readFile(join(ROOT, 'assets/chat.webp'), 'base64')
const heart = await readFile(join(ROOT, 'assets/heart-mark.webp'), 'base64')
const sidebarMark = await readFile(join(ROOT, 'assets/sidebar-mark.webp'), 'base64')
const chatMark = await readFile(join(ROOT, 'assets/chat-mark.webp'), 'base64')
const companion = await readFile(join(ROOT, 'assets/chat-companion.webp'), 'base64')
const generatedBody = [
  '/**',
  ' * Generated by scripts/build.mjs from assets/chat.webp,',
  ' * assets/heart-mark.webp, assets/sidebar-mark.webp,',
  ' * assets/chat-mark.webp and assets/chat-companion.webp —',
  ' * do not edit by hand; rerun `npm run build`.',
  ' * Bundle-scope module: plain consts, no import/export statements.',
  ' */',
  `const CHAT_BACKDROP = 'data:image/webp;base64,${chat}'`,
  '',
  `const RASTER_HEART_MARK = 'data:image/webp;base64,${heart}'`,
  '',
  `const SIDEBAR_MARK = 'data:image/webp;base64,${sidebarMark}'`,
  '',
  `const CHAT_MARK = 'data:image/webp;base64,${chatMark}'`,
  '',
  `const CHAT_COMPANION = 'data:image/webp;base64,${companion}'`,
  '',
].join('\n')
await write('src/client/background-art.generated.js', generatedBody)

/* 2. Client bundle assembly. */
const index = await read('src/client/index.js')
const css = await read('src/client/aemeath.css')

const cssInjection = [
  '// Stylesheet inlined at materialization with the loader-owned tag',
  '// convention: <style data-plugin> is removed by the HMR driver on unload.',
  `const AEMEATH_CSS = ${JSON.stringify(css)};`,
  'if (typeof document !== "undefined" && document.querySelector(\'style[data-plugin-css="\' + ' + JSON.stringify(CSS_TAG_ID) + ' + \'"]\') === null) {',
  '  const cssTag = document.createElement("style");',
  `  cssTag.dataset.plugin = ${JSON.stringify(PACKAGE_NAME)};`,
  `  cssTag.dataset.pluginCss = ${JSON.stringify(CSS_TAG_ID)};`,
  '  cssTag.textContent = AEMEATH_CSS;',
  '  document.head.appendChild(cssTag);',
  '}',
].join('\n')

const client = [
  `window.__ModuleLoader__.load({`,
  `\tid: ${JSON.stringify(PACKAGE_NAME)},`,
  '\tfactory: (require) => {',
  '\t\tvar module = { exports: {} };',
  '\t\tvar exports = module.exports;',
  '\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });',
  region('src/client/background-art.generated.js', indentBlock(generatedBody)),
  region('src/client/aemeath.css (inlined)', indentBlock(cssInjection)),
  region('src/client/index.js', indentBlock(index)),
  '\t\texports.apply = apply;',
  '\t\treturn module.exports;',
  '\t}',
  '});',
  '',
].join('\n')
await write('lib/client.js', client)

/* 3. Host entry passthrough. */
await write('lib/index.js', await read('src/index.js'))

const size = (p) => stat(join(ROOT, p)).then(s => s.size)
const fmt = (bytes) => `${(bytes / 1024).toFixed(0)} KiB`
console.log(`built ${relative(process.cwd(), join(ROOT, 'lib/client.js'))} (${fmt(await size('lib/client.js'))})`)
console.log(`built ${relative(process.cwd(), join(ROOT, 'lib/index.js'))} (${fmt(await size('lib/index.js'))})`)
console.log(`generated src/client/background-art.generated.js (${fmt(await size('src/client/background-art.generated.js'))})`)
